name: Supabase Keep Alive
on:
  schedule:
    - cron: '0 0 * * 1,4' # Jalan tiap Senin & Kamis biar makin aman
  workflow_dispatch: # Biar lo bisa klik tombol "Run" manual buat ngetes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Supabase
        run: |
          curl -i -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/barangs?select=*" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"